version: "3.9"

services:
  mlflow:
    build:
      context: ./build/mlflow_build
      dockerfile: Dockerfile
    image: mlflow_server:1.0
    depends_on:
      - postgres
    ports:
      - "5050:5000"
    environment:
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: 23wesdxc
      MLFLOW_TRACKING_URI: "http://localhost:5050"
    entrypoint: bash -c "mlflow server --backend-store-uri postgresql://postgres:postgres@postgres:5432/postgres --host 0.0.0.0 --port 5000"

  postgres:
    image: postgres:16.3-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
